- name: change route53
  route53:
    state: present
    zone: wread.com
    record: www.wread.com
    failover: PRIMARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "{{ NEW_ALIAS }}"
    wait: yes
    health_check: "7e7ba130-6f68-4838-908a-d1e7867cbb19"
